#!/usr/bin/env bash
#
# bitcoin-lib.sh - Bitcoin-specific utilities for Bitcoin Core operations
#
# Sources core utilities and provides bitcoin-specific functions

source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

# This library provides idempotent functions for managing Bitcoin Core infrastructure:
# - User management (create/remove bitcoin users safely)
# - Bitcoin operator deployment (directories, configuration, always-current resources)
# - Process management (start/stop bitcoin daemon)
#
# DESIGN PHILOSOPHY:
# - All functions are idempotent (safe for repeated execution)
# - Deploy operations always ensure current state matches desired state
# - Clobber operations safely remove resources when they exist
# - Scripts fail fast with clear error messages when dependencies are missing
#

# Bitcoin-specific functions (core utilities sourced from lib.sh)

# Check if bitcoin daemon is running
is_bitcoin_running() {
    local username="$1"

    if ! id "$username" &>/dev/null; then
        return 1
    fi

    # Check for bitcoind process owned by the user, excluding pgrep itself
    if sudo -u "$username" pgrep -f "^bitcoind -conf" >/dev/null 2>&1; then
        return 0
    else
        return 1
    fi
}

# Stop bitcoin daemon
stop_bitcoin() {
    local username="$1"

    if ! is_bitcoin_running "$username"; then
        log_echo "✓ No bitcoin daemon running for $username"
        return 0
    fi

    local home_dir="/home/$username"
    if sudo -u "$username" test -f "$home_dir/halt-bitcoin"; then
        sudo su - "$username" -c "./halt-bitcoin" || true
        log_echo "✓ Bitcoin daemon stopped"
    else
        log_echo "⚠ halt-bitcoin script not found, attempting direct process termination"
        if sudo su - "$username" -c "bitcoin-cli -conf=$home_dir/bitcoin.conf stop" 2>/dev/null; then
            log_echo "✓ Bitcoin daemon stopped via RPC"
        elif sudo su - "$username" -c "pkill -f '^bitcoind -conf'" 2>/dev/null; then
            log_echo "✓ Bitcoin daemon process terminated"
        else
            log_echo "✓ No bitcoin daemon process found"
        fi
    fi
}

# Idempotent bitcoin operator removal
clobber_bitcoin_operator() {
    local username="$1"

    if id "$username" &>/dev/null; then
        # Stop bitcoin daemon if running
        stop_bitcoin "$username"

        # Remove bitcoin-specific files before generic user removal
        sudo -u "$username" rm -rf \
            "/home/$username/data" \
            "/home/$username/logs/bitcoin.log" \
            "/home/$username/run-bitcoin" \
            "/home/$username/halt-bitcoin" \
            "/home/$username/bitcoin.conf" 2>/dev/null || true
        log_echo "✓ Removed bitcoin operator files for: $username"

        # Remove logrotate configuration
        if [[ -f "/etc/logrotate.d/bitcoin-$username" ]]; then
            sudo rm "/etc/logrotate.d/bitcoin-$username"
            log_echo "✓ Removed logrotate config for $username"
        fi

        # Use generic user removal
        clobber_user "$username"
    fi
}

# Generate bitcoin configuration
generate_bitcoin_config() {
    local username="$1"
    local network_mode="$2"
    local data_dir="/home/$username/data"
    local rpc_port="8332"
    local p2p_port="8333"

    # Adjust ports and chain name based on network
    local bitcoin_chain="$network_mode"
    case "$network_mode" in
    testnet)
        bitcoin_chain="test"
        rpc_port="18332"
        p2p_port="18333"
        ;;
    testnet4)
        bitcoin_chain="testnet4"
        rpc_port="48332"
        p2p_port="48333"
        ;;
    signet)
        bitcoin_chain="signet"
        rpc_port="38332"
        p2p_port="38333"
        ;;
    regtest)
        bitcoin_chain="regtest"
        rpc_port="18443"
        p2p_port="18444"
        ;;
    devnet)
        # For devnet, use regtest mode
        bitcoin_chain="regtest"
        rpc_port="18443"
        p2p_port="18444"
        ;;
    main|mainnet)
        bitcoin_chain="main"
        rpc_port="8332"
        p2p_port="8333"
        ;;
    esac

    # Use configurable RPC credentials (must be provided)
    local rpc_user="${BITCOIN_RPC_USER:-bitcoin}"
    local rpc_password="${BITCOIN_RPC_PASSWORD:-}"

    if [[ -z "$rpc_password" ]]; then
        log_echo "ERROR: BITCOIN_RPC_PASSWORD must be set"
        return 1
    fi

    cat <<EOF
# Bitcoin Core configuration
# Generated by valops bitcoin-init

# Network configuration
chain=$bitcoin_chain
datadir=$data_dir

# Global settings
server=1
dbcache=512
maxconnections=125
maxuploadtarget=0
debug=0
logtimestamps=1
disablewallet=1
listen=1
discover=1

# Network-specific settings
$(if [ "$bitcoin_chain" != "main" ]; then
    echo "[$bitcoin_chain]"
fi)
rpcbind=127.0.0.1
rpcport=$rpc_port
rpcuser=$rpc_user
rpcpassword=$rpc_password
port=$p2p_port
EOF
}

# Idempotent bitcoin operator initialization (one-time setup)
init_bitcoin_operator() {
    local username="$1"
    local network_mode="$2"
    local home_dir="/home/$username"

    # Create user and directories (idempotent)
    create_user "$username"
    sudo -u "$username" mkdir -p "$home_dir"/{data,logs}

    # Generate configuration
    log_echo "Generating bitcoin configuration..."
    generate_bitcoin_config "$username" "$network_mode" | sudo tee "$home_dir/bitcoin.conf" >/dev/null
    sudo chown "$username:$username" "$home_dir/bitcoin.conf"
    sudo chmod 600 "$home_dir/bitcoin.conf"

    # Update scripts and configuration
    update_bitcoin_operator "$username"

    # Enable log rotation
    ensure_logrotate_enabled "$username" "bitcoin"

    # Configure P2P firewall rules if enabled
    ensure_bitcoin_p2p_enabled "$username" "$network_mode"

    # Apply Bitcoin Knots banlist if enabled
    apply_knots_banlist "$username"
}

# Update bitcoin operator configuration (assumes init_bitcoin_operator was run)
update_bitcoin_operator() {
    local username="$1"
    local home_dir="/home/$username"

    log_echo "Updating bitcoin operator configuration for $username..."

    # Deploy run-bitcoin script
    sudo tee "$home_dir/run-bitcoin" >/dev/null <<'EOF'
#!/bin/bash
set -euo pipefail

# Ensure we're running from the user's home directory
cd "$HOME"

# Configuration
CONFIG_FILE="$HOME/bitcoin.conf"
LOG_FILE="$HOME/logs/bitcoin.log"

# Function to log and echo
log_echo() {
    echo "run-bitcoin: $@" | tee -a "$LOG_FILE"
}

# Verify environment is set up correctly
if [[ ! -f "$CONFIG_FILE" ]]; then
    log_echo "ERROR: Configuration file $CONFIG_FILE does not exist. Run bitcoin-init first."
    exit 1
fi

if [[ ! -d "$HOME/logs" ]]; then
    log_echo "ERROR: Logs directory $HOME/logs does not exist. Run bitcoin-init first."
    exit 1
fi

# Log startup
log_echo "$(date): Starting Bitcoin Core daemon..."
log_echo "Using configuration: $CONFIG_FILE"

# Start bitcoind with config file
exec bitcoind -conf="$CONFIG_FILE" "$@" >> "$LOG_FILE" 2>&1
EOF

    # Deploy halt-bitcoin script
    sudo tee "$home_dir/halt-bitcoin" >/dev/null <<'EOF'
#!/bin/bash
set -euo pipefail

# Function to log and echo
log_echo() {
    echo "halt-bitcoin: $@" | tee -a "$HOME/logs/bitcoin.log"
}

log_echo "$(date): Stopping Bitcoin Core daemon..."

# Try graceful shutdown via RPC first
if bitcoin-cli -conf="$HOME/bitcoin.conf" stop 2>/dev/null; then
    log_echo "✓ Bitcoin daemon stopped gracefully via RPC"
else
    # Fall back to signal-based termination
    if pkill -SIGTERM -f "^bitcoind -conf" 2>/dev/null; then
        log_echo "✓ Bitcoin daemon stopped via SIGTERM"
    else
        log_echo "✓ No bitcoin daemon process found"
    fi
fi
EOF

    # Set permissions
    sudo chmod +x "$home_dir/run-bitcoin" "$home_dir/halt-bitcoin"
    sudo chown "$username:$username" "$home_dir/run-bitcoin" "$home_dir/halt-bitcoin"

    log_echo "✓ Updated bitcoin operator configuration for $username"
}

# Configure Bitcoin P2P firewall rules (similar to ensure_gossip_enabled for validators)
ensure_bitcoin_p2p_enabled() {
    local username="$1"
    local network_mode="$2"

    # Check if P2P should be enabled (default: disabled for security)
    local enable_p2p="${BITCOIN_P2P_ENABLED:-false}"

    if [[ "$enable_p2p" != "true" ]]; then
        log_echo "ℹ Bitcoin P2P disabled (BITCOIN_P2P_ENABLED=false)"
        log_echo "  → Outbound-only operation (secure for validators)"
        return 0
    fi

    # Determine P2P port based on network
    local p2p_port="8333"
    case "$network_mode" in
    testnet)
        p2p_port="18333"
        ;;
    testnet4)
        p2p_port="48333"
        ;;
    signet)
        p2p_port="38333"
        ;;
    regtest|devnet)
        p2p_port="18444"
        ;;
    main|mainnet)
        p2p_port="8333"
        ;;
    esac

    # Check if ufw is installed and active
    if ! command -v ufw >/dev/null 2>&1; then
        log_echo "⚠ UFW not installed, skipping P2P firewall configuration"
        return 0
    fi

    # Get current ufw status
    local ufw_status=$(sudo ufw status | head -1 | awk '{print $2}')

    if [ "$ufw_status" = "active" ]; then
        log_echo "UFW is active, enabling Bitcoin P2P port $p2p_port..."

        # Check if P2P port is already allowed
        if ! sudo ufw status numbered | grep -q "$p2p_port/tcp"; then
            sudo ufw allow "$p2p_port/tcp" comment "Bitcoin P2P port ($network_mode)" >/dev/null 2>&1 || true
            log_echo "✓ Opened Bitcoin P2P port $p2p_port"
            log_echo "  → Can now accept inbound peer connections"
        else
            log_echo "✓ Bitcoin P2P port $p2p_port already allowed"
        fi
    else
        log_echo "✓ UFW not active, no P2P firewall configuration needed"
    fi
}

# Apply Bitcoin Knots banlist to prevent restrictive relay policies
apply_knots_banlist() {
    local username="$1"
    local home_dir="/home/$username"
    local banlist_file="$home_dir/banlist.json"

    # Check if Knots banlist should be applied (default: enabled for better relay)
    local enable_banlist="${BITCOIN_KNOTS_BANLIST:-true}"

    if [[ "$enable_banlist" != "true" ]]; then
        log_echo "ℹ Bitcoin Knots banlist disabled (BITCOIN_KNOTS_BANLIST=false)"
        return 0
    fi

    log_echo "Applying Bitcoin Knots banlist for better relay policies..."

    # Download latest banlist from GitHub
    local banlist_url="https://raw.githubusercontent.com/aeonBTC/Knots-Banlist/main/banlist.json"

    if command -v curl >/dev/null 2>&1; then
        if curl -s -f "$banlist_url" -o "/tmp/banlist.json.tmp" 2>/dev/null; then
            # Verify it's valid JSON
            if jq empty "/tmp/banlist.json.tmp" 2>/dev/null; then
                sudo mv "/tmp/banlist.json.tmp" "$banlist_file"
                sudo chown "$username:$username" "$banlist_file"
                sudo chmod 600 "$banlist_file"

                # Count banned addresses
                local ban_count=$(jq 'length' "$banlist_file" 2>/dev/null || echo "unknown")
                log_echo "✓ Applied Bitcoin Knots banlist ($ban_count addresses banned)"
                log_echo "  → Prevents restrictive relay policies that affect fee estimation"
            else
                log_echo "⚠ Downloaded banlist is not valid JSON, skipping"
                rm -f "/tmp/banlist.json.tmp"
            fi
        else
            log_echo "⚠ Failed to download Bitcoin Knots banlist from GitHub"
        fi
    else
        log_echo "⚠ curl not available, cannot download Bitcoin Knots banlist"
    fi
}
